로그인 테스트 및 유저 조회 api 테스트
Do-it-Comm-it/DoitCommit-front pull request #23
Opened 2022-01-19 09:07 UTC by junmin-Chang

- [x] `useAuthentication.ts` 수정  -> { authorize }로 user Set 
- [x] `service/firebase.ts`  삭제
- [x] 사용 안하는 모듈 삭제 `swr` ,`firebase`
- [x] 로그인 후 새로고침하면 깜빡임이 발생해서 Router.body 쪽 `React.Suspense`로 Wrap
- [x] 백엔드 응답에 맞게 user typing 수정 
- [x] 엑세스토큰 만료 -> 새로운 요청 시 리프레쉬토큰으로 새로운 엑세스토큰 발급 후 이전에 실패한 요청 재개하는 것 테스트 완료   

useAuthentication 훅이나 App.tsx에서 유저 정보 받아오는 것이 잘한게 맞는 지 모르겠습니다.. 원래 하던 방식으로 다시 변경해야할지.. 효진님께서 한번 봐주시면 감사하겠습니다.

2022-01-21 14:04 UTC, alexrider94 requested changes

2022-01-21 15:34 UTC, junmin-Chang commented on src/routes/Route.tsx
> +      </React.Suspense>
@alexrider94 혹시 서버 켜고 로그인이 안되시나요??

2022-01-21 17:37 UTC, junmin-Chang commented on src/routes/Route.tsx
> +      </React.Suspense>
@alexrider94 어떻게 안되는 지 알려주시면 제가 일어나서 수정하겠습니다!

2022-01-21 17:45 UTC, junmin-Chang commented on src/layouts/App/index.tsx
>    }, [authorize]);
@alexrider94 혹시 이런식으로 수정하면 될까요?

2022-01-21 18:19 UTC, junmin-Chang commented on src/recoil/atom/user.ts
>  });
@alexrider94 Recoil 공식문서를 살펴보니 atom내에서 default값을 selector를 이용해 바로 뽑을 수 있더라구요 이 방법이 더 괜찮아보이는데 어떻게 생각하시나요?

2022-01-22 01:07 UTC, alexrider94 commented on src/recoil/atom/user.ts
>  });
넵! 이 방법이 좋은것같아요

2022-01-22 01:08 UTC, alexrider94 commented on src/routes/Route.tsx
> +      </React.Suspense>
최근 브랜치 쓰니까 해결됬네요!

2022-01-22 01:08 UTC, merged