Fix/article
Do-it-Comm-it/DoitCommit-front pull request #60
Opened 2022-08-15 13:10 UTC by gbwlxhd97

1. 아티클 북마크 좋아요 react-query Mutation stale 에러 수정 : 기존의 쿼리 unique key 값이 달라서 오류가 발생한 것 같았습니다.
2. 아티클 페이지 아티클 (기획,개발,디자인 전체 분류) 퍼블리싱
3. 아티클 페이지  정렬 드롭다운 (최신순,좋아요순,조회수순) 퍼블리싱

Organisms/Board/Articles 컴포넌트에서  213라인에
해당 styled-components에 기존과다르게 인터페이스를 추가해줬는데 props를 전달해주는 과정에서
계속 콘솔에 ``
`Warning: React does not recognize the `prop` prop on a DOM element.`
에러가 발생해서 구글링해보니까 
styled-components v4 버전의 버그라고 하더라구요
data-* attributes 속성을 권장한다고 해서 저도 밑에처럼 해보니 오류는 안나더라구요.
혹시 효진님도 이런경험 있으셨을때 어떻게 해결하셨는지 궁금한데 styled-components 사용하면서 저와같은 경험이 있으셨나요?

저의 기존 코드는 Organisms/Board/Articles 컴포넌트 89번 ,213 라인에서 밑에 코드와같이 사용하던도중 콘솔에 에러가 발생했어요
`
<FilterOpener
    isOpener={isOpener}
    onClick={() => {
      setIsOpener((prev) => !prev);
    }}
>

const FilterOpener = styled(OpenerSVG)<{isOpener}>`
  & > path {
    stroke: ${({ theme }) => theme.colors.primary.default};
  }
  cursor: pointer;
      transform: ${({isOpener}) => isOpener ? rotate(-180deg) rotate(0deg) }
`;

`
![image](https://user-images.githubusercontent.com/49021925/184637730-4004a445-134b-437b-93a7-ffff7ab9d56d.png)

2022-08-16 13:30 UTC, alexrider94 requested changes
1. 필터 메뉴 클릭시에 바깥쪽 클릭시 닫게 하도록 가능할까요? 

만들어둔 hook이 있는데 아마도 `useOutsideClick`  이거 사용하면 될꺼에요.

2. 필터 메뉴 클릭시에 아이콘 클릭으로 필터가 열리는데 `FilterButton` 이 부분으로 확장해서 열리게 하면 좋을것같습니다. 

- 텍스트 클릭시에도 필터 메뉴가 확장되도록 하면 될것같아요.

2022-08-17 03:10 UTC, gbwlxhd97 commented on src/components/Organisms/Board/Articles.tsx
> +const FilterOpener = styled(OpenerSVG)<OpenerType>`
오.. 넵넵 밑에 방식으로 적용하고
필터 메뉴 클릭에 텍스트범위까지 포함시키고
바깥 클릭 닫힘까지 적용하고 다시 pr올릴게요!

2022-08-22 00:47 UTC, gbwlxhd97 commented
말씀해주신 작업사항 수정하여 다시 올렸습니다.!
게다가 useOutsideClick custom hook이 아주 용이하네요 ㅎㅎ

2022-08-22 10:43 UTC, alexrider94 approved these changes
https://usehooks.com/ 여기에 쓸만한 hooks들이 많아요 ㅎㅎ
고생하셨습니다!

2022-08-22 10:43 UTC, merged